### PR TITLE
Added Alternate / Improved town screens depencies

### PR DESCRIPTION
**Pull request by GeorgeK1ng**

### CODE REVIEW

**Comment by Olegmods** [comment]
Are you sure that all towns look good with LotRD screens? I feel that the Ziggurat (the Couatl's building) should look bad with LotRD assets.

**Comment by GeorgeK1ng** [comment]
Not too bad at all. My goal was not to disable whole Tides of Wars addition. Of course it can be easily disabled / customized. As we have now new pack with more town themes which interacts together. It will be cool to have alternate themes for them too in compatibility submods for ToW. Few building looks like they needs some touch, so let's ask some graphics guys for improvements. 

image

image

image

image

image

image

image

image

image

**Comment by Olegmods** [comment]
> Not too bad at all. My goal was not to disable whole Tides of Wars addition. Of course it can be easily disabled / customized. As we have now new pack with more town themes which interacts together. It will be cool to have alternate themes for them too in compatibility submods for ToW. Few building looks like they needs some touch, so let's ask some graphics guys for improvements.

I guess the improvements from the "graphics guys" isn't a thing that we should rely on, since they are busy with their own projects right now. I suggest making Inferno, Castle, Rampart and Stronghold conflicts. Other looks not too bad.

> image

Btw. I guess Conflux's LotRD screen should soft depend on HotA.

**Comment by GeorgeK1ng** [comment]
Just check PRs for all town screens. All conflicts and depencies should be fine. Just ToW one are currently commented out.

In Conflux are visible some glitches - I have not identified source for now.

What's wrong with Rampart?

Castle - building def needs to add snow
Inferno - building def needs to remove background
Stronghold - building def needs recolor, but doesn't look so bad

Your included picture is not visible.

**Comment by Olegmods** [comment]
> Just check PRs for all town screens. All conflicts and depencies should be fine. Just ToW one are currently commented out.

I just suggest to comment the aforemented three until they can be fixed.

> In Conflux are visible some glitches - I have not identified source for now.

It's due to HotA's Altar of Air being used instead of OH3/LotRD one. Hota made a different background for Conflux.

> What's wrong with Rampart?

Some pixels from the original Rampart sky is visible. On the screens, at least.

**Pull request merged**
